{ action: 'created',
  issue: 
   { url: 'https://api.github.com/repos/cctuan/gulp-css-merger/issues/2',
     repository_url: 'https://api.github.com/repos/cctuan/gulp-css-merger',
     labels_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/issues/2/labels{/name}',
     comments_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/issues/2/comments',
     events_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/issues/2/events',
     html_url: 'https://github.com/cctuan/gulp-css-merger/issues/2',
     id: 172300292,
     number: 2,
     title: 'test',
     user: 
      { login: 'cctuan',
        id: 1499206,
        avatar_url: 'https://avatars.githubusercontent.com/u/1499206?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/cctuan',
        html_url: 'https://github.com/cctuan',
        followers_url: 'https://api.github.com/users/cctuan/followers',
        following_url: 'https://api.github.com/users/cctuan/following{/other_user}',
        gists_url: 'https://api.github.com/users/cctuan/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/cctuan/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/cctuan/subscriptions',
        organizations_url: 'https://api.github.com/users/cctuan/orgs',
        repos_url: 'https://api.github.com/users/cctuan/repos',
        events_url: 'https://api.github.com/users/cctuan/events{/privacy}',
        received_events_url: 'https://api.github.com/users/cctuan/received_events',
        type: 'User',
        site_admin: false },
     labels: [],
     state: 'open',
     locked: false,
     assignee: null,
     assignees: [],
     milestone: null,
     comments: 3,
     created_at: '2016-08-21T01:59:16Z',
     updated_at: '2016-08-21T10:16:05Z',
     closed_at: null,
     body: '' },
  comment: 
   { url: 'https://api.github.com/repos/cctuan/gulp-css-merger/issues/comments/241249345',
     html_url: 'https://github.com/cctuan/gulp-css-merger/issues/2#issuecomment-241249345',
     issue_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/issues/2',
     id: 241249345,
     user: 
      { login: 'cctuan',
        id: 1499206,
        avatar_url: 'https://avatars.githubusercontent.com/u/1499206?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/cctuan',
        html_url: 'https://github.com/cctuan',
        followers_url: 'https://api.github.com/users/cctuan/followers',
        following_url: 'https://api.github.com/users/cctuan/following{/other_user}',
        gists_url: 'https://api.github.com/users/cctuan/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/cctuan/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/cctuan/subscriptions',
        organizations_url: 'https://api.github.com/users/cctuan/orgs',
        repos_url: 'https://api.github.com/users/cctuan/repos',
        events_url: 'https://api.github.com/users/cctuan/events{/privacy}',
        received_events_url: 'https://api.github.com/users/cctuan/received_events',
        type: 'User',
        site_admin: false },
     created_at: '2016-08-21T10:16:05Z',
     updated_at: '2016-08-21T10:16:05Z',
     body: 'test' },
  repository: 
   { id: 34876559,
     name: 'gulp-css-merger',
     full_name: 'cctuan/gulp-css-merger',
     owner: 
      { login: 'cctuan',
        id: 1499206,
        avatar_url: 'https://avatars.githubusercontent.com/u/1499206?v=3',
        gravatar_id: '',
        url: 'https://api.github.com/users/cctuan',
        html_url: 'https://github.com/cctuan',
        followers_url: 'https://api.github.com/users/cctuan/followers',
        following_url: 'https://api.github.com/users/cctuan/following{/other_user}',
        gists_url: 'https://api.github.com/users/cctuan/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/cctuan/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/cctuan/subscriptions',
        organizations_url: 'https://api.github.com/users/cctuan/orgs',
        repos_url: 'https://api.github.com/users/cctuan/repos',
        events_url: 'https://api.github.com/users/cctuan/events{/privacy}',
        received_events_url: 'https://api.github.com/users/cctuan/received_events',
        type: 'User',
        site_admin: false },
     private: false,
     html_url: 'https://github.com/cctuan/gulp-css-merger',
     description: 'concat all css from html into one',
     fork: false,
     url: 'https://api.github.com/repos/cctuan/gulp-css-merger',
     forks_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/forks',
     keys_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/keys{/key_id}',
     collaborators_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/collaborators{/collaborator}',
     teams_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/teams',
     hooks_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/hooks',
     issue_events_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/issues/events{/number}',
     events_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/events',
     assignees_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/assignees{/user}',
     branches_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/branches{/branch}',
     tags_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/tags',
     blobs_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/git/blobs{/sha}',
     git_tags_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/git/tags{/sha}',
     git_refs_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/git/refs{/sha}',
     trees_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/git/trees{/sha}',
     statuses_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/statuses/{sha}',
     languages_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/languages',
     stargazers_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/stargazers',
     contributors_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/contributors',
     subscribers_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/subscribers',
     subscription_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/subscription',
     commits_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/commits{/sha}',
     git_commits_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/git/commits{/sha}',
     comments_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/comments{/number}',
     issue_comment_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/issues/comments{/number}',
     contents_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/contents/{+path}',
     compare_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/compare/{base}...{head}',
     merges_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/merges',
     archive_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/{archive_format}{/ref}',
     downloads_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/downloads',
     issues_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/issues{/number}',
     pulls_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/pulls{/number}',
     milestones_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/milestones{/number}',
     notifications_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/notifications{?since,all,participating}',
     labels_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/labels{/name}',
     releases_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/releases{/id}',
     deployments_url: 'https://api.github.com/repos/cctuan/gulp-css-merger/deployments',
     created_at: '2015-04-30T21:00:20Z',
     updated_at: '2015-05-09T17:07:58Z',
     pushed_at: '2016-08-21T01:50:48Z',
     git_url: 'git://github.com/cctuan/gulp-css-merger.git',
     ssh_url: 'git@github.com:cctuan/gulp-css-merger.git',
     clone_url: 'https://github.com/cctuan/gulp-css-merger.git',
     svn_url: 'https://github.com/cctuan/gulp-css-merger',
     homepage: null,
     size: 3,
     stargazers_count: 1,
     watchers_count: 1,
     language: 'JavaScript',
     has_issues: true,
     has_downloads: true,
     has_wiki: true,
     has_pages: false,
     forks_count: 0,
     mirror_url: null,
     open_issues_count: 2,
     forks: 0,
     open_issues: 2,
     watchers: 1,
     default_branch: 'master' },
  sender: 
   { login: 'cctuan',
     id: 1499206,
     avatar_url: 'https://avatars.githubusercontent.com/u/1499206?v=3',
     gravatar_id: '',
     url: 'https://api.github.com/users/cctuan',
     html_url: 'https://github.com/cctuan',
     followers_url: 'https://api.github.com/users/cctuan/followers',
     following_url: 'https://api.github.com/users/cctuan/following{/other_user}',
     gists_url: 'https://api.github.com/users/cctuan/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/cctuan/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/cctuan/subscriptions',
     organizations_url: 'https://api.github.com/users/cctuan/orgs',
     repos_url: 'https://api.github.com/users/cctuan/repos',
     events_url: 'https://api.github.com/users/cctuan/events{/privacy}',
     received_events_url: 'https://api.github.com/users/cctuan/received_events',
     type: 'User',
     site_admin: false } }